#!/bin/bash

PROJECT_ROOT="${GITPOD_REPO_ROOT:-../}"

echo "Running pre-commit hooks on ${PROJECT_ROOT}"

# Running tests and test coverage report
pytest --cov $PROJECT_ROOT

# Formatting code
black $PROJECT_ROOT
